### ISSUE TITLE
No module named `configuration_falcon`

### ISSUE THREAD

**Issue by fahadh4ilyas** [linfeng93/BiTA#1]
Why the script must import file that is not even in the repo? I'm currently testing this

```bash
sh scripts/run_sft-pt2_llama2-7b-chat.sh
```

and somehow I got this error:

```python
Traceback (most recent call last):
  File "/home/fahadh/BiTA/src/train_bash.py", line 2, in <module>
    from llmtuner import run_exp
  File "/home/fahadh/BiTA/src/llmtuner/__init__.py", line 3, in <module>
    from llmtuner.api import create_app
  File "/home/fahadh/BiTA/src/llmtuner/api/__init__.py", line 1, in <module>
    from llmtuner.api.app import create_app
  File "/home/fahadh/BiTA/src/llmtuner/api/app.py", line 9, in <module>
    from llmtuner.chat import ChatModel
  File "/home/fahadh/BiTA/src/llmtuner/chat/__init__.py", line 1, in <module>
    from llmtuner.chat.stream_chat import ChatModel
  File "/home/fahadh/BiTA/src/llmtuner/chat/stream_chat.py", line 8, in <module>                                                                                from llmtuner.tuner.core import get_infer_args, load_model_and_tokenizer
  File "/home/fahadh/BiTA/src/llmtuner/tuner/__init__.py", line 1, in <module>                                                                                  from llmtuner.tuner.tune import export_model, run_exp
  File "/home/fahadh/BiTA/src/llmtuner/tuner/tune.py", line 5, in <module>
    from llmtuner.tuner.core import get_train_args, get_infer_args, load_model_and_tokenizer                                                                  File "/home/fahadh/BiTA/src/llmtuner/tuner/core/__init__.py", line 2, in <module>
    from llmtuner.tuner.core.loader import load_model_and_tokenizer
  File "/home/fahadh/BiTA/src/llmtuner/tuner/core/loader.py", line 21, in <module>                                                                              from modeling_falcon_if import FalconForCausalLM
  File "/home/fahadh/BiTA/src/modeling_falcon_if.py", line 44, in <module>                                                                                      from configuration_falcon import FalconConfig
ModuleNotFoundError: No module named 'configuration_falcon'
```

**Comment by linfeng93** [comment]
Hi, @fahadh4ilyas 

sorry, we've noticed the bug you mentioned in the script (the need to import Falcon-related modules when training llama2). 
The "No module named" error you encountered occurs only during the initial stage of importing modules in the script. Temporarily resolving this issue can be achieved by commenting out the corresponding lines of code.

As the Chinese New Year holiday draws near, our current schedule prevents us from promptly addressing this bug in the code. However, please rest assured that we will prioritize fixing it as soon as we find the time. 

Thank you for your understanding.

**Comment by linfeng93** [comment]
https://github.com/linfeng93/BiTA/pull/4#issue-2137860469
Thanks to @noah-kim-theori
